### PR TITLE
Update ML Workbench notebooks to include feature exploration and feature sensitivity analysis.

### PR DESCRIPTION
**Pull request by qimingj**

### CODE REVIEW

**Comment by brandondutra** [comment]
I like it. I think we need to make two things clear: 1) LIME is a small new package, so use it at your own risk. 2) Say what we learned by using LIME (need to remove stop words)

in the text classification notebook

* 'news_train_data' is not defined --> s/news_train_data/news_test_data/ You could also get the data from the vocab file in the analysis folder.

* add comments on what's the value of the x-axis. Check this is true, and maybe add something like 
"LIME perturbes the input values, and runs each datapoint through the TensorFlow model. LIME then makes a linear model with a variable for every input feature and uses the TensorFlow prediction as the target. The values on the x-axis are the coefficients of LIME's linear model. This means large positive values correspond to words that the TensorFlow model considers useful for labeling a class while large negative numbers signals that the TensorFlow model  believes those words do not belong to the class. This overview description of LIME is true as of version 0.1.1.23, but as this package is new please consult with the latest documentation for its usage. Our use of LIME is for illustration and for gaining some insight into the TensorFlow model, we don't claim LIME is the best or correct tool for validating a model. " The point of this paragraph is to say 1) what is lime doing as no one knows lime because it is new....we don't want to say "because LIME says it's good/bad it must be so", 2) warn people this is a new small package and not standard like matplotlib.

* add text saying something like "In the LIME plots above, we see that some words that have little meaning like 'hi', 'say' or 'because' show up (your exact results may differ), this suggests that our TensorFlow model is incorrectly assigning meaning to these words. One solution is to remove these 'stop words' from the data in notebook one." The point here is that we should use LIME to make a conclusion.

* add comment that the data is the first 5 rows from the cleaned test file.

* worked in FireFox, so that's nice.

**Comment by brandondutra** [comment]
1.0 Download and clean the StackOverflow 2017 survey data.ipynb

* add comments saying the next two cells produce plots that are only correctly rendered in Chrome,  due to a bug in Facets. Please use the Chrome browser to view the Facets plots.

**Comment by brandondutra** [comment]
ok, final notebook: flowers

* I think the same warnings about LIME need to be made, but much louder as we have no idea how they perturb the image. There is some magical image processing going on. The regions that LIME outlines as being important may not correspond to how the TF model sees the image. LIME does not explain TF, it is a model for guessing what TF is doing. This point needs to be made very clear. 

* do you have an image example of TF getting it wrong, like what you did for the text model?

**Comment by qimingj** [comment]
Thanks for the comments! Most of them are followed, except:

I did not comment much on LIME (such as it is new) since it is a third party component.
I did not do text analysis (such as 'hi', 'say' are stop words). Would rather leave it to users since my judgement may not be accurate.

PTAL.

**Pull request merged**
