### PR TITLE
Add a tutorial to list Stackdrive groups, and read metrics for them.

### PR DESCRIPTION
**Pull request by supriyagarg**

### CODE REVIEW

**Comment by supriyagarg** [comment]
This PR will not pass travis tests till https://github.com/googledatalab/pydatalab/pull/65 is part of the datalab build.

**Comment by supriyagarg** [comment]
@ojarjur: This PR is also ready to go. It can go in after #32. The travis tests don't fully pass on my fork, but the Monitoring notebooks get converted fine:

https://travis-ci.org/supriyagarg/notebooks/builds/165346055#L425

**Comment by ojarjur** [comment]
@supriyagarg 

Regarding the Travis failures in your fork... do you have an old Datalab image specified in the "DOCKER_IMAGE" environment variable?

If so, then removing that variable and re-running the tests will probably fix the issue.

If not, then it might have been a transient failure, and re-running the test may fix it.

**Comment by supriyagarg** [comment]
I don't have the environment variable "DOCKER_IMAGE" set in my settings. And tests are indeed flaky - they sometimes pass, and sometimes give an error in one or more of the following:

	./tutorials/Machine Learning/Census/1. Feature.ipynb
	./tutorials/BigQuery/Importing and Exporting Data.ipynb
	./tutorials/Storage/Storage APIs.ipynb

Note: for the groups notebook  to pass, there is an extra requirement that I have added to .test.sh:

    # 5. Created a Stackdriver account, and a Stackdriver group containing one or
    #     more Google Compute Engine VMs (this is required by the monitoring 'Group
    #     metrics' notebook).

**Comment by ojarjur** [comment]
Sorry for the delay getting this submitted; I had to double check that our test project satisfied the requirements for it, and that in turn revealed [a bug in pydatalab](https://github.com/googledatalab/pydatalab/pull/83) that needed to be fixed.

This LGTM, so thanks.

**Pull request merged**
