### PR TITLE
Updated the Getting started notebook for Monitoring.

### PR DESCRIPTION
**Pull request by supriyagarg**
This notebook will work without any changes as long as:
1. A default project is set.
2. The project has at least 1 GCE instance.

The above requirements are also explicitly mentioned at the beginning of the notebook, so that the user is aware of them.

### CODE REVIEW

**Comment by parthea** [comment]
`'This project must have atleast one GCE Instance.'` 
`'atleast'` => `'at least'`

**Comment by parthea** [comment]
Potentially the following message could be made an error:

Could change
```
print 'This project has no GCE instances. The remaining notebook will raise errors!'
```
to
```
  import sys
  sys.stderr.write('This project has no GCE instances. The remaining notebook will raise errors!')
```

**Comment by parthea** [comment]
Potentially the variables could have longer names to help with readability.
```
q1 = q.select_metrics(instance_name=instance_names[0])
```
could become
```
cpu_usage_single_instance = cpu_usage.select_metrics(instance_name=instance_names[0])
```

**Comment by parthea** [comment]
Just a few minor observations. 

Very useful notebook! I like the heat map.

**Comment by supriyagarg** [comment]
Thanks for the comments @parthea! I have made the suggested changes, and added other variable names to be more descriptive as well. Please take a look, and I can squash the commits once you are done.

**Comment by parthea** [comment]
LGTM. Thanks!

**Comment by supriyagarg** [comment]
@parthea: I synced my branch with master, and squashed the commit with the edits for readability. It is ready to merge now.

**Comment by parthea** [comment]
cc @chmeyers

**Pull request merged**
